### ISSUE TITLE
This is perfect for a project I'm working on

### ISSUE THREAD

**Issue by mblode** [JensDebergh/things-calendar#2]
Sorry, this isn't an issue just wanted to say this is an awesome project! (I couldn't find your email or personal site) I am currently developing a React version of Things 3 and this will work perfectly for my project. Thank you!

Check out the work in progress version here: https://things-mobx-qsljjkybik.now.sh

I'd love to hear your thoughts 😄

**Comment by JensDebergh** [comment]
Hey Matthew!

Love the idea that someone is already using this library in a side project. Let me know if you have any problems so I can create a proper fix for it.

As for the link I think it's broken. I'm unable to access your project, but would love to try it out!


Edit:

Link works again and it looks really nice! Keep me updated on the status.

Kind regards
Jens
